import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

class Auth with ChangeNotifier {
  var store = FirebaseFirestore.instance.collection('Vehicle');
  List<String> cities_list = [
    'Agartala',
    'Agra',
    'Ahmedabad',
    'Ahmednagar',
    'Aizawl',
    'Ajmer',
    'Akola',
    'Aligarh',
    'Allahabad',
    'Alwar',
    'Amaravathi',
    'Ambattur',
    'Ambernath',
    'Amravati',
    'Amritsar',
    'Anantapur',
    'Arrah',
    'Asansol',
    'Aurangabad,',
    'Aurangabad,',
    'Avadi',
    'Bagaha',
    'Bally,',
    'Bangalore',
    'Baranagar',
    'Barasat',
    'Bardhaman',
    'Bareilly',
    'Bathinda',
    'Begusarai',
    'Belgaum',
    'Bellary',
    'Berhampur',
    'Bettiah',
    'Bhagalpur',
    'Bharatpur,',
    'Bhatpara',
    'Bhavnagar',
    'Bhilai',
    'Bhilwara',
    'Bhimavaram"',
    'Bhiwandi',
    'Bhopal',
    'Bhubaneswar',
    'Bihar',
    'Bijapur,',
    'Bikaner',
    'Bilaspur,',
    'Bokaro',
    'Buxar',
    'Chandigarh',
    'Chandrapur',
    'Chennai',
    'Chhapra',
    'Coimbatore',
    'Cuttack',
    'Danapur',
    'Darbhanga',
    'Davanagere',
    'Dehradun',
    'Dehri',
    'Delhi',
    'Deoghar',
    'Dewas',
    'Dhanbad',
    'Dhule',
    'Durg',
    'Durgapur,',
    'Erode',
    'Eluru',
    'Etawah',
    'Faridabad',
    'Farrukhabad',
    'Firozabad',
    'Gandhidham',
    'Gaya,',
    'Ghaziabad,',
    'Gopalpur,',
    'Gorakhpur',
    'Gudivada"',
    'Gulbarga',
    'Guntur',
    'Gurgaon',
    'Guwahati',
    'Gwalior',
    'Hajipur',
    'Hapur',
    'Haridwar',
    'Hisar,',
    'Hosur"',
    'Howrah',
    'Hubballi-Dharwad',
    'Hyderabad',
    'Ichalkaranji',
    'Imphal',
    'Indore',
    'Jabalpur',
    'Jaipur',
    'Jalandhar',
    'Jalgaon',
    'Jalna',
    'Jamalpur',
    'Jammu',
    'Jamnagar',
    'Jamshedpur',
    'Jehanabad',
    'Jhansi',
    'Jodhpur',
    'Junagadh',
    'Kadapa',
    'Kakinada',
    'Kalyan-Dombivali',
    'Kamarhati',
    'Kanpur',
    'Karimnagar',
    'Karnal',
    'Katihar',
    'Kirari',
    'Kishanganj',
    'Kochi',
    'Kolhapur',
    'Kolkata',
    'Kollam',
    'Korba,',
    'Kota,',
    'Kozhikode',
    'Kulti',
    'Kurnool',
    'Latur',
    'Loni,',
    'Lucknow',
    'Ludhiana',
    'Machilipatnam"',
    'Madurai',
    'Maheshtala',
    'Malegaon',
    'Mangalore',
    'Mathura',
    'Mau',
    'Meerut',
    'Mira-Bhayandar',
    'Mirzapur',
    'Moradabad',
    'Motihari',
    'Mumbai',
    'Munger',
    'Muzaffarnagar',
    'Muzaffarpur',
    'Mysore',
    'Nagpur',
    'Nanded',
    'Nashik',
    'Navi',
    'Nellore',
    'New',
    'Nizamabad,',
    'Noida',
    'North',
    'Ozhukarai',
    'Pali,',
    'Panihati',
    'Panipat',
    'Parbhani',
    'Patiala',
    'Patna',
    'Pimpri-Chinchwad',
    'Pondicherry',
    'Pune',
    'Purnia',
    'Raichur',
    'Raipur',
    'Rajahmundry',
    'Rajkot',
    'Rajpur',
    'Ramagundam',
    'Rampur,',
    'Ranchi',
    'Ratlam',
    'Rewa,',
    'Rohtak',
    'Rourkela',
    'Sagar,',
    'Saharanpur',
    'Saharsa',
    'Salem,',
    'Sangli-Miraj',
    'Sasaram',
    'Satara',
    'Satna',
    'Shahjahanpur',
    'Shivamogga',
    'Sikar',
    'Siliguri',
    'Siwan',
    'Solapur',
    'Sonipat',
    'South',
    'Sri',
    'Srinagar',
    'Surat',
    'Tadepalligudem"',
    'Tenali',
    'Thane',
    'Thiruvananthapuram',
    'Thoothukudi',
    'Thrissur',
    'Tiruchirappalli',
    'Tirunelveli',
    'Tirupati',
    'Tiruppur',
    'Tiruvottiyur',
    'Tumkur',
    'Udaipur',
    'Ujjain',
    'Ulhasnagar',
    'Vadodara',
    'Varanasi',
    'Vasai-Virar',
    'Vijayawada',
    'Visakhapatnam',
    'Vizianagaram',
    'Warangal',
    'Miryalaguda',
    'Bongaigaon',
    'Jorhat',
    'Dibrugarh',
    'Tinsukia',
    'Silchar',
    'Nagaon',
    'Tezpur'
  ];
  List<String> vehicle_category = [
    'Tata Ace',
    '3 Wheeler',
    'Tata 407',
    'Pickup 8FT',
    'Others',
  ];
  List<String> capacity = [
    '0 - 1 Tone',
    '1 - 2 Tone',
    '2 - 3 Tone',
    '3 + Tone',
  ];

  var auth = FirebaseAuth.instance;
  bool get isAuth {
    if (FirebaseAuth.instance.currentUser == null)
      return false;
    else
      return true;
  }

  Future<void> authlogin(PhoneAuthCredential credential) async {
    await FirebaseAuth.instance
        .signInWithCredential(credential)
        .then((value) async {});
    notifyListeners();
    return null;
  }

  Future<void> authlogout() async {
    await FirebaseAuth.instance.signOut();

    notifyListeners();
  }

  Future<void> register(
    personal,
    vehicle,
    driver,
  ) async {
    await store.doc(vehicle['Vehicle No']).set({
      'Owner Name': personal['Name'],
      'Owner Address':
          '${personal['permanent_address']} ${personal['pincode']}',
      'City': personal['city'],
      'Owner Adhar Card': personal['adharcard'],
      'Owner Phone': personal['phone'],
      'Vehicle No': vehicle['Vehicle No'],
      'Vehicle Category': vehicle['category'],
      'Vehicle Upload': vehicle['capacity'],
    }).whenComplete(() async {
      if (driver == null) {
        await store.doc(vehicle['Vehicle No']).update({
          'Driver': 'Self',
        });
      } else
        await store.doc(vehicle['Vehicle No']).update({
          'Driver': driver['Name'],
          'Driver Address':
              '${driver['permanent_address']} ${driver['pincode']}',
          'Driver Phone': driver['phone'],
          'Driver Adhar': driver['adharcard'],
        });
    });
  }
}
